version: "3.8"

services:
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped

  db:
    image: mariadb:10.5
    container_name: guac-db
    environment:
      MYSQL_ROOT_PASSWORD: StrongRootPass123
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: StrongDBPass123
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: db
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacuser
      MYSQL_PASSWORD: StrongDBPass123
    depends_on:
      - guacd
      - db
    restart: unless-stopped
